In [1]:
import numpy as np 

In [2]:
mat1 = np.array([[1,2,3], 
                 [4,5,6], 
                 [7,8,9]])
mat1[1,2]

np.int64(6)

In [ ]:
# transpose matrix 
mat1.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
# aayz aaml matrix kolhaa zeros 
mat = np.zeros((3, 4 ))
mat

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
angle = np.arange(0 , 361 , 90)
angle


array([  0,  90, 180, 270, 360])

In [ ]:
# identity matrix 
I = np.identity(3 , dtype="float32")
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

In [118]:
# random matrix 
np.random.random((3 ,3 ))


array([[0.23876639, 0.33526087, 0.96458817],
       [0.9675545 , 0.08903539, 0.12311363],
       [0.85420279, 0.91341474, 0.45181171]])

In [ ]:
# random matrix bs mhded mn 0 le 11 msh haigblyy rakm aziad mn 10 
np.random.randint(0 , 11  , (5 , 5 ))

array([[ 2,  7,  4, 10,  4],
       [ 1,  2,  5, 10,  6],
       [ 5, 10,  6,  5,  2],
       [ 8,  3,  8,  8,  9],
       [ 3,  8,  8,  5,  9]], dtype=int32)

In [119]:
a = ['ali ' , 3 ,  'joe' , False ]
np.random.choice(a , size=(3 , 5))

array([['ali ', 'False', 'joe', '3', '3'],
       ['joe', 'ali ', '3', 'False', 'ali '],
       ['joe', '3', 'joe', 'joe', '3']], dtype='<U21')

In [121]:
mat_1 = np.ones((3 , 4))
mat_2 = np.zeros((5 , 3))

np.savez('np_file' , Ones_Mat = mat_1 , Zeros_Mat = mat_2)


In [ ]:
with np.load('np_file.npz')as file :

    mat_1 = file ['Ones_mat']
    mat_2 = file ['Zeros_mat']

print(mat_1)
print(mat_2)    

KeyError: 'Ones_mat is not a file in the archive'

In [10]:
def array_reshape(arr , row = -1 , col = -1 ) : 
    try : 
        arr = np.arr(arr) 
        return arr.reshape(row , col)
    except (TypeError , ValueError) as e :
        raise ValueError(f"invalid reshape operation : {e}") 

In [ ]:
vec =  [1 , 2 , 3 , 4 , 5 , 6 ]
print(array_reshape(vec , 2 , 3 ))

NameError: name 'np' is not defined

In [127]:
v1 = np.array ([1 , 2 , 3 , 4 , 5])
v2 = np.array ([2 , 3 , 0 , 5 , 3])
np.allclose(v1 , v2 , )

False