# NumPy Programming Assignment


Part 1: Smart Array Factory
Task: Create a function that allows students to generate specific array types quickly using built-in NumPy methods.


In [4]:
import numpy as np

def array_factory(mode, shape, value=None):
    if mode == 'zeros':
        return np.zeros(shape)
    
    elif mode == 'ones':
        return np.ones(shape)
    
    elif mode == 'full':
        return np.full(shape, value)
    
    elif mode == 'identity':
        return np.eye(shape)
    
    else:
        return "Invalid mode"


Part 2: The secure_reshape_and_stack Function.

This function demonstrates how to handle data integration by transforming a flat data structure into a matrix and then combining it with an existing dataset


In [5]:
import numpy as np

def secure_reshape_and_stack(data1, data2, new_shape):
    try:
        # 1. Convert inputs to NumPy arrays (ndarrays)
        arr1 = np.array(data1)
        arr2 = np.array(data2)

        # 2. Reshape arr1 lel shape el gded elly el user ba3ato
        reshaped_arr1 = arr1.reshape(new_shape)

        # 3. Vertical Stacking (nlza2hom fo2 ba3d)
        # Lazem el etnen ykon lehom nefs el 3ard (number of columns)
        combined_dataset = np.vstack((reshaped_arr1, arr2))

        return combined_dataset

    except ValueError as e:
        # Law el reshaped_arr1 msh mo3'taleb m3a arr2 f el columns, haytalla3 error
        raise ValueError(f"Company-grade Error: {e}")

part-3 The apply_threshold Function.

This function demonstrates Conditional Access and Modification, which are primarily used in data cleaning and processing. It follows the logic of identifying specific elements based on a boolean condition and replacing them efficiently.


In [6]:
import numpy as np

def apply_threshold(arr, threshold, replacement_value=-1):
    # 1. Convert input to a numpy array (ndarray)
    arr = np.array(arr)

    # 2. Define the condition: elementwise comparison 
    # De bt-check kol raqam f el array law akbar men aw yesawy el threshold
    condition = (arr >= threshold)
    
    # 3. Apply Modification using np.where() 
    # np.where(condition, value_if_true, value_if_false)
    # Law el condition sa7 (True), 7ot el replacement_value. 
    # Law ghalat (False), seb el raqam el asly zay ma hwa (arr).
    modified_arr = np.where(condition, replacement_value, arr)
    
    return modified_arr

TestCase


In [4]:
import numpy as np

# --- 1. Lazem el function tkon maktouba el awel ---
def secure_reshape_and_stack(data1, data2, new_shape):
    try:
        arr1 = np.array(data1)
        arr2 = np.array(data2)
        reshaped_arr1 = arr1.reshape(new_shape)
        combined_dataset = np.vstack((reshaped_arr1, arr2))
        return combined_dataset
    except ValueError as e:
        raise ValueError(f"Company-grade Error: {e}")

# --- 2. Ba3den n-nady 3aleeha ---
branch_a = [1, 2, 3, 4, 5, 6] 
branch_b = [[7, 8, 9], 
            [10, 11, 12]]

# Hna el computer kda haykoun "3aref" el function khalas
final_report = secure_reshape_and_stack(branch_a, branch_b, (2, 3))

print(final_report)
print("Shape bta3 el report:", final_report.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Shape bta3 el report: (4, 3)


In [ ]:
v = np.array([1, 2, 3])
result = apply_threshold(v, 2, -20)
print(result)




NameError: name 'apply_threshold' is not defined